import Head from 'next/head';
import Image from 'next/image';

import styles from "@/styles/index.module.scss";

import logoMain from "@/public/logos/logo-um.png";
import arrowRight from "@/public/icons/arrow_right_white.png"

import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';

import { robotoFlex } from '@/fonts/font';

import { useDispatch, useSelector } from 'react-redux';

import { dataJobs } from "@/redux/dataMain/dataMainSlice";
import { newSearch } from "@/redux/searchHome/searchHomeSlice";

import { useEffect, useState } from 'react';

import axios from 'axios';

import { Router, useRouter } from 'next/router';

export default function Home() {
  const [nameJob, setNameJob] = useState();
  const [countrys, setCountrys] = useState();
  const [citys, setCitys] = useState();
  const [dataLocal, setDataLocal] = useState();

  const [countrySelect , setCountrySelect] = useState();
  const [citySelect , setCitySelect] = useState();
  
  const dispatch = useDispatch();
  const router = useRouter();

  async function handleJobs(){
    const configApi = {
      method: 'get',
      url: 'https://home-office-jobs-6a2f088fb390.herokuapp.com/job/offers',
      headers: {
        'X-Custom-Jobs': 'my-secret-endpoint-1@@89'
      }
    }
    
    axios(configApi)
    .then((response) => {
      dispatch(dataJobs(response.data))
      const data = response.data.map((item) => ({
        pais: item.pais,
        cidade: item.cidade
      }))
      const dataCountrys = data.map((item) => item.pais)

      setDataLocal(data)
      setCountrys([...new Set(dataCountrys)])
    })
    .catch((error) => {
      return null
    })
  }

  async function handleCitys(){
    if(!countrys){
      return null
    }else{
      const citys = dataLocal.filter((item) => item.pais === countrySelect)

      setCitys(citys)
    }
  }

  function sendDataFilter(e){
    e.preventDefault()
    dispatch(newSearch({
        title: nameJob,
        country: countrySelect,
        city: citySelect
      }
    ))
    router.push("/vaga-filtrada")
  }

  useEffect(() => { 
    handleJobs()
  }, [])

  useEffect(() => { 
    handleCitys()
  }, [countrySelect])

  return (
    <div className={robotoFlex.className}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div id={styles.mainPage}>
        <div id={styles.content}>
          <main id={styles.mainContent}>
            <div id={styles.tituloPrincipal}>
              <div>
                <Image id={styles.fotoLogoMain} src={logoMain} alt="Logo HomeOfficeVagas" height={200} width={200} />
              </div>
              <div id={styles.titulo}>
                <h1 id={styles.tituloDaPagina}>Na Home Office Vagas, você encontra sua vaga Home Office num piscar de olhos.</h1>
                <p id={styles.textoDoTitulo}>Venha conseguir o seu emprego com a gente!</p>
              </div>
              <Image id={styles.fotoSetaaDireita} src={arrowRight} alt="seta a direita" width={200} />
            </div>
            <div id={styles.boxSearch}>
              <h2 id={styles.tituloForm}>Busque suas vagas aqui!</h2>
              <form id={styles.formPesquisa} onSubmit={sendDataFilter} action="#">
                <input className={styles.entradasForm} onChange={(e) => setNameJob(e.target.value)} type="text" placeholder="Busque por Titulo" />
                <select className={styles.entradasForm} onChange={(e) => setCountrySelect(e.target.value)}>
                  {countrys ? <>
                    <option disabled>Países carregados</option>
                    {countrys.map((item) => (
                      <option key={item}>{item}</option>
                    ))}
                  </> : <option>Carregando países...</option>}
                </select>
                <select className={styles.entradasForm} onChange={(e) => setCitySelect(e.target.value)} value={citySelect}>
                  {citys ? <>
                    <option>Escolha uma cidade</option>
                    {citys.map((item) => (
                      <option key={item.id}>{item.cidade}</option>
                    ))}
                  </> : <option>Escolha um país...</option>}
                </select>
                <button id={styles.btnBuscar}>Buscar</button>
              </form>
            </div>
          </main>
          <nav id={styles.navigationCountrys}>
            <a className={styles.countrys} href="">Brasília</a>
            <a className={styles.countrys} href="">Sydney</a>
            <a className={styles.countrys} href="">Salvador</a>
            <a className={styles.countrys} href="">Seul</a>
            <a className={styles.countrys} href="">New York</a>
            <a className={styles.countrys} href="">Montreal</a>
            <a className={styles.countrys} href="">Paris</a>
            <a className={styles.countrys} href="">Johannesburgo</a>
            <a className={styles.countrys} href="">São Paulo</a>
          </nav>
          <Footer/>
        </div>
      </div>
    </div>
  )
}
