import Head from 'next/head';
import Image from 'next/image';

import styles from "@/styles/index.module.scss";

import logoMain from "@/public/imgs/logo-um.png";
import arrowRight from "@/public/icons/arrow_right_white.png"
import Header from '@/components/header/Header';

import { robotoFlex } from '@/fonts/font';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div id={styles.mainPage} className={robotoFlex.className}>
        <div id={styles.conteudo}>
          <main>
            <div id={styles.mainContent}>

              <div>
                <div>
                  <Image src={logoMain} alt="Logo HomeOfficeVagas" height={200} width={200}/>
                </div>
                <h1 id={styles.tituloDaPagina}>Na Home Office Vagas, você encontra sua vaga Home Office num piscar de olhos.</h1>
                <Image src={arrowRight} alt="" width={200}/>
              </div>

              <div id={styles.boxPesquisa}>
                <h2 id={styles.tituloForm}>Busque suas vagas aqui!</h2>
                <form id={styles.formPesquisa} action="#">
                  <input className={styles.entradasForm} type="text" placeholder="Busque por Titulo"/>
                  <select className={styles.entradasForm} name="" id="">
                    <option value="">Argentina</option>
                    <option value="">Uruguai</option>
                    <option value="">Egito</option>
                  </select>
                  <select className={styles.entradasForm} name="" id="">
                    <option value="">Montevídeu</option>
                  </select>
                  <button id={styles.btnBuscar}>Buscar</button>
                </form>
              </div>

            </div>
          </main>
          <footer>
            <nav id={styles.navegacao}>
              <a className={styles.paises} href="">Brasília</a>
              <a className={styles.paises} href="">Sydney</a>
              <a className={styles.paises} href="">Salvador</a>
              <a className={styles.paises} href="">Seul</a>
              <a className={styles.paises} href="">New York</a>
              <a className={styles.paises} href="">Montreal</a>
              <a className={styles.paises} href="">Paris</a>
              <a className={styles.paises} href="">Johannesburgo</a>
              <a className={styles.paises} href="">São Paulo</a>
            </nav>
          </footer>
        </div>
      </div>
    </div>
  )
}
