import Head from 'next/head';
import Image from 'next/image';

import styles from "@/styles/index.module.scss";

import logoMain from "@/public/logos/logo-um.png";
import arrowRight from "@/public/icons/arrow_right_white.png"

import Header from '@/components/header/Header';

import { robotoFlex } from '@/fonts/font';
import Footer from '@/components/footer/Footer';

export default function Home() {

  return (
    <div className={robotoFlex.className}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div id={styles.mainPage}>
        <div id={styles.content}>
          <main id={styles.mainContent}>
            <div id={styles.tituloPrincipal}>
              <div>
                <Image id={styles.fotoLogoMain} src={logoMain} alt="Logo HomeOfficeVagas" height={200} width={200} />
              </div>
              <div id={styles.titulo}>
                <h1 id={styles.tituloDaPagina}>Na Home Office Vagas, você encontra sua vaga Home Office num piscar de olhos.</h1>
                <p id={styles.textoDoTitulo}>Venha conseguir o seu emprego com a gente!</p>
              </div>
              <Image id={styles.fotoSetaaDireita} src={arrowRight} alt="seta a direita" width={200} />
            </div>
            <div id={styles.boxSearch}>
              <h2 id={styles.tituloForm}>Busque suas vagas aqui!</h2>
              <form id={styles.formPesquisa} action="#">
                <input className={styles.entradasForm} type="text" placeholder="Busque por Titulo" />
                <select className={styles.entradasForm} name="" id="">
                  <option value="">Argentina</option>
                  <option value="">Uruguai</option>
                  <option value="">Egito</option>
                </select>
                <select className={styles.entradasForm} name="" id="">
                  <option value="">Montevídeu</option>
                </select>
                <button id={styles.btnBuscar}>Buscar</button>
              </form>
            </div>
          </main>
          <nav id={styles.navigationCountrys}>
            <a className={styles.countrys} href="">Brasília</a>
            <a className={styles.countrys} href="">Sydney</a>
            <a className={styles.countrys} href="">Salvador</a>
            <a className={styles.countrys} href="">Seul</a>
            <a className={styles.countrys} href="">New York</a>
            <a className={styles.countrys} href="">Montreal</a>
            <a className={styles.countrys} href="">Paris</a>
            <a className={styles.countrys} href="">Johannesburgo</a>
            <a className={styles.countrys} href="">São Paulo</a>
          </nav>
          <Footer/>
        </div>
      </div>
    </div>
  )
}
